/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BranchAndBound.BranchAndBound;
import Simplex.Ferramentas;
import Simplex.Modelo;
import Simplex.Simplex;
import java.util.Arrays;
import javax.swing.table.TableModel;

/**
 *
 * @author j�lia
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTextField1 = new javax.swing.JTextField();
        MinBtn = new javax.swing.JRadioButton();
        StartBtn = new javax.swing.JButton();
        MaxBtn = new javax.swing.JRadioButton();
        labelProblema = new javax.swing.JLabel();
        labelVariaveis = new javax.swing.JLabel();
        labelRestricoes = new javax.swing.JLabel();
        labelNumRestricoes = new javax.swing.JLabel();
        numVar = new javax.swing.JSpinner();
        numRestricoes = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaRestr = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaZ = new javax.swing.JTable();
        simplex = new javax.swing.JRadioButton();
        branch = new javax.swing.JRadioButton();
        labelProblema1 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Otimiza��o de Sistemas");

        MinBtn.setText("Minimiza��o");
        MinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinBtnActionPerformed(evt);
            }
        });

        StartBtn.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        StartBtn.setText("Otimizar!");
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });

        MaxBtn.setSelected(true);
        MaxBtn.setText("Maximiza��o");
        MaxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxBtnActionPerformed(evt);
            }
        });

        labelProblema.setText("Problema de:");

        labelVariaveis.setText("N�mero de Vari�veis: ");

        labelRestricoes.setText("Restri��es:");

        labelNumRestricoes.setText("N�mero de Restri��es:");

        jLabel2.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        jLabel2.setText("Daniel Reis, Felipe Botrel, J�lia Gobbo e Mateus Silveira");

        jButton1.setText("Confirmar Valores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelaRestr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X1", "X2", "Operador", "Valor"
            }
        ));
        jScrollPane3.setViewportView(tabelaRestr);

        jLabel3.setText("Fun��o Objetiva: ");

        tabelaZ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "X1", "X2"
            }
        ));
        jScrollPane1.setViewportView(tabelaZ);

        simplex.setText("Simplex Comum ");
        simplex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simplexActionPerformed(evt);
            }
        });

        branch.setSelected(true);
        branch.setText("Simplex com Inteiros");
        branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchActionPerformed(evt);
            }
        });

        labelProblema1.setText("Utilizar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelVariaveis)
                                            .addComponent(labelNumRestricoes)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(numRestricoes, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                            .addComponent(numVar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelProblema)
                                        .addGap(18, 18, 18)
                                        .addComponent(MinBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MaxBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelProblema1)
                                        .addGap(18, 18, 18)
                                        .addComponent(simplex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(branch))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(151, 151, 151)
                                .addComponent(StartBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelRestricoes)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProblema)
                    .addComponent(MinBtn)
                    .addComponent(MaxBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(simplex)
                        .addComponent(branch))
                    .addComponent(labelProblema1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVariaveis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numRestricoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumRestricoes)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRestricoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int nV = this.getNumVar()>0 ? this.getNumVar() : 0;
        int nR = this.getNumRestricoes()>0 ? this.getNumRestricoes() : 0;
        
        // atualizar tabela da funcao objetiva
        String[]tabNomes = new String[nV];
        Object[][]valores = new Object[1][nV];
        
        // preencher nome das colunas da f.o.
        for(int i=0;i<tabNomes.length;i++) {
            tabNomes[i]="X"+(i+1);
        }
        
        // autopreencher valores das variaveis da f.o.
        for(int i=0;i<valores[0].length;i++) {
            valores[0][i]=0;
        }
        
        tabelaZ.setModel(new javax.swing.table.DefaultTableModel(
            valores,
            tabNomes
        ));
        
        // atualizar tabela das restricoes
        tabNomes = new String[nV+2];
        valores = new Object[nR][nV+2];
        
        // preencher nome das colunas das restricoes
        for(int i=0;i<tabNomes.length;i++) {
            tabNomes[i]="X"+(i+1);
        }
        
        // autopreencher valores das variaveis das restricoes
        for(int i=0;i<valores.length;i++) {
            for(int j=0;j<valores[i].length;j++) {
                valores[i][j]=0;
            }
        }
        
        tabNomes[tabNomes.length-2]="Operador";
        tabNomes[tabNomes.length-1]="Valor";

        tabelaRestr.setModel(new javax.swing.table.DefaultTableModel(
            valores,
            tabNomes
        ));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinBtnActionPerformed
        // TODO add your handling code here:
        MaxBtn.setSelected(false);
        minmax = -1;
    }//GEN-LAST:event_MinBtnActionPerformed

    private void MaxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxBtnActionPerformed
        // TODO add your handling code here:
        MinBtn.setSelected(false);
        minmax = 1;
    }//GEN-LAST:event_MaxBtnActionPerformed

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed
        // TODO add your hln("Z");andling code here:
        int min = this.getMinMax();
	int n = this.getNumVar();
	double[] z = this.getZ();
        double[][] r = this.getRestricoes();
        if(simplex.isSelected()){
            Simplex s = new Simplex(new Modelo(min, z, r, n));
            Simplex.ResultadoSimplex resp = s.processar(true);
        }else{
            BranchAndBound bb = new BranchAndBound(new Modelo(min,z,r,n));   
            bb.processar();
        }
    }//GEN-LAST:event_StartBtnActionPerformed

    private void simplexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simplexActionPerformed
        branch.setSelected(false);
    }//GEN-LAST:event_simplexActionPerformed

    private void branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchActionPerformed
        simplex.setSelected(false);
    }//GEN-LAST:event_branchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton MaxBtn;
    private javax.swing.JRadioButton MinBtn;
    private javax.swing.JButton StartBtn;
    private javax.swing.JRadioButton branch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelNumRestricoes;
    private javax.swing.JLabel labelProblema;
    private javax.swing.JLabel labelProblema1;
    private javax.swing.JLabel labelRestricoes;
    private javax.swing.JLabel labelVariaveis;
    private javax.swing.JSpinner numRestricoes;
    private javax.swing.JSpinner numVar;
    private javax.swing.JRadioButton simplex;
    private javax.swing.JTable tabelaRestr;
    private javax.swing.JTable tabelaZ;
    // End of variables declaration//GEN-END:variables
    private int minmax = 1;
    
    /**
     * Recupera n�mero de restri��es
     */
    public int getNumRestricoes() {
        return (Integer) numRestricoes.getValue();
    }
    
    /**
     * Recupera n�mero de vari�veis
     */
    public int getNumVar() {
        return (Integer) numVar.getValue();
    }
    
    /**
     * Recupera tipo do problema
     * @return 1 para maximiza��o e -1 para minimiza��o
     */
    public int getMinMax() {
        return minmax; 
    }
    
    /**
     * Recupera valores das variaveis da fun��o objetiva
     */
    public double[] getZ()
    {
        TableModel model = tabelaZ.getModel();
        double[] fo = new double[model.getColumnCount()];
        
        for(int i=0;i<model.getColumnCount();i++) {
            try{
                fo[i]=Double.parseDouble(model.getValueAt(0,i).toString());
            }
            catch (Exception e) {
                System.out.println("getZ: Valor inv�lido na posi��o: "+i);
                fo[i]=0.0;
            }
        }
        return fo;
    }
    
    /**
     * Recupera as restri��es da interface 
     */
    public double[][] getRestricoes(){
        
        TableModel model = this.tabelaRestr.getModel();
        
        double valor, operador, var;
        double[][]restricoes = new double[model.getRowCount()][model.getColumnCount()-1];
        
        for(int i=0;i<model.getRowCount();i++) {
            valor = Double.parseDouble(""+model.getValueAt(i,model.getColumnCount()-1));
            if((""+model.getValueAt(i,model.getColumnCount()-2)).equals("<")||
                    (""+model.getValueAt(i,model.getColumnCount()-2)).equals("<=")){
                operador = 1;
            }else if((""+model.getValueAt(i,model.getColumnCount()-2)).equals(">")||
                    (""+model.getValueAt(i,model.getColumnCount()-2)).equals(">=")){
                operador = -1;
            }else{
                operador = 0;
            }
                        
            restricoes[i][0] = (operador>0) ? valor : valor*(-1);
            
            for(int j=0;j<model.getColumnCount()-2;j++)
            {
                var = Double.parseDouble(""+model.getValueAt(i,j));
                restricoes[i][j+1] = (operador>0) ? var : var*(-1); 
            }
        }
        return restricoes; 
    }
}
