/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Simplex.Ferramentas;
import Simplex.Simplex;

/**
 *
 * @author Daniel
 */
public class Relatorio extends javax.swing.JFrame {
    private int minmax;
    private double [] operadores;
    /**
     * Creates new form Relatório
     */
    public Relatorio(Simplex s) {
        
        this.matriz = s.getMatrizSup();
        this.varBasicas = s.getVarBasicas();
        this.varNaoBasicas = s.getVarNaoBasicas(); 
        this.minmax = s.getModelo().getMinmax();
        this.operadores = s.getModelo().getOperadores();
        initComponents();
        criarTabela(); 
    }
    
    public void criarTabela(){
    
        int numVar = varBasicas.length + varNaoBasicas.length + 1; 
        
        String [][] modelo = new String[numVar][3]; 
        String [][] modelo2 = new String[numVar][3]; 
        
        modelo[0][0]="Função Objetiva";
        modelo[0][1]=""+-1*minmax*matriz[0][0];
        
        for(int i=1;i<numVar;i++){
            modelo[i][0] = "X" + (i); 
        }
        
        for(int i=0;i<varBasicas.length;i++){
            modelo2[i][0] = "R" + (i+1); 
            modelo2[i][2] = "" + 0;
            modelo2[i][1] = "" + 0;
        }
        
        for(int i=0;i<varBasicas.length;i++){
            modelo[varBasicas[i]][1] = "" + matriz[i+1][0];
            if(varBasicas[i] >= varBasicas.length){
                modelo2[varNaoBasicas[i]-varBasicas.length][2] = "" + -1*minmax*matriz[0][i+1]; 
            }
        }
        
        for(int i=0;i<varNaoBasicas.length;i++){
            modelo[varNaoBasicas[i]][1] = "" + 0; 
        }
        
               
        for(int i=0;i<varNaoBasicas.length;i++){
            if(varNaoBasicas[i] >= varBasicas.length){
                modelo2[varNaoBasicas[i]-varBasicas.length][2] = "" + -1*minmax*matriz[0][i+1]; 
            }
        }
        
        
        
        Ferramentas.printMatriz(matriz);
        String[]titulos = new String []{"Variável","Valor","Variação"};
        
        String[]titulos2 = new String []{"Restrição","Valor","Preço Sombra"};
        
        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            modelo,
            titulos
        ));
        
        tabelaResultado1.setModel(new javax.swing.table.DefaultTableModel(
            modelo2,
            titulos2
        ));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResultado = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaResultado1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado");

        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Variável", "Valor" , "Variação", "Preço Sombra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaResultado);

        tabelaResultado1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Variável", "Valor" , "Variação", "Preço Sombra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaResultado1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    private double [][] matriz;
    private int [] varBasicas;
    private int [] varNaoBasicas; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaResultado;
    private javax.swing.JTable tabelaResultado1;
    // End of variables declaration//GEN-END:variables
}
