/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Simplex.Ferramentas;
import Simplex.Simplex;

/**
 *
 * @author Daniel
 */
public class Relatorio extends javax.swing.JFrame {
    private int minmax;
    private double [] operadores;
    private Simplex s;
    /**
     * Creates new form Relatório
     */
    public Relatorio(Simplex s) {
        
        this.matriz = s.getMatrizSup();
        this.varBasicas = s.getVarBasicas();
        this.varNaoBasicas = s.getVarNaoBasicas(); 
        this.minmax = s.getModelo().getMinmax();
        this.operadores = s.getModelo().getOperadores();
        this.s = s;
        initComponents();
        criarTabela(); 
    }
    
    public void criarTabela(){
    
        int numVar = varBasicas.length + varNaoBasicas.length + 1; 
        if(s.getTime()<1000)
            jLabel3.setText(""+(s.getTime())+" milisegundos");
        else
            jLabel3.setText(""+(s.getTime()/1000)+" segundos");
        String [][] modelo = new String[numVar][4]; 
        
        modelo[0][0]="Função Objetiva";
        modelo[0][1]=""+-1*minmax*matriz[0][0];
        
        for(int i=1;i<numVar;i++){
            modelo[i][0] = "0"; 
            modelo[i][1] = "0"; 
            modelo[i][2] = "0"; 
            modelo[i][3] = "0"; 
            
        }
        
        for(int i=0;i<varBasicas.length;i++){
            modelo[varBasicas[i]][1] = "" + matriz[i+1][0];
        }
        
        for(int i=0;i<varNaoBasicas.length;i++){
            modelo[varNaoBasicas[i]][1] = "" + 0; 
        }  
        
        for(int i=0;i<varNaoBasicas.length;i++){
            if(varNaoBasicas[i] >= varBasicas.length){
                modelo[varNaoBasicas[i]][3] = "" + -1*minmax*matriz[0][i+1]; 
            }else{
                modelo[varNaoBasicas[i]][3] = "" + 0;
            }
        }
        
        for(int i=0;i<varNaoBasicas.length;i++){
            if(varNaoBasicas[i] <= varBasicas.length){
                modelo[varNaoBasicas[i]][2] = "" + -1*minmax*matriz[0][i+1]; 
            }else{
                modelo[varNaoBasicas[i]][2] = "" + 0;
            }
        }
        
        for(int i = 0;i<varBasicas.length;i++){
            modelo[varBasicas[i]][3] = "" + 0; 
        }
        
        Ferramentas.printMatriz(matriz);
        String[]titulos = new String []{"Variável","Valor","Variação", "Preço Sombra"};
        
        
        
        Ferramentas.printMatriz(matriz);
        
        String[]titulos2 = new String []{"Restrição","Valor","Preço Sombra"};
        
        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            modelo,
            titulos
        ));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResultado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado");

        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Variável", "Valor" , "Variação", "Preço Sombra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaResultado);

        jLabel2.setText("Tempo de Execução:");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    private double [][] matriz;
    private int [] varBasicas;
    private int [] varNaoBasicas; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaResultado;
    // End of variables declaration//GEN-END:variables
}
